name: root_fear
description: Package to detect root on Android.
version: 0.0.1
repository: https://www.github.com/iandis/root-fear
issue_tracker: https://www.github.com/iandis/root-fear/issues

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.2.3"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  plugin:
    platforms:
      android:
        package: app.iandis.root_fear
        pluginClass: RootFearPlugin
